# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9zQYhhNNUJ5th1tU-h0d1FMvRtPz1Z0
"""

import streamlit as st
import yfinance as yf
import pandas as pd

# Set Streamlit page config
st.set_page_config(page_title="SSC Money", page_icon="💸", layout="centered")

# ---------------- Wallet Section ----------------
st.markdown("""
    <h1 style='text-align: center; color: #4CAF50;'>💸 SSC Money</h1>
""", unsafe_allow_html=True)

st.markdown("""
    <h2 style='color: #008080;'>💰 Wallet Overview</h2>
""", unsafe_allow_html=True)

# Simulated balance and transactions
balance = 52710
transactions = [
    {"date": "2025-04-29", "desc": "Added ₹500", "amount": 500},
    {"date": "2025-04-28", "desc": "Spent ₹100 on SIP", "amount": -100},
    {"date": "2025-04-27", "desc": "Added ₹250", "amount": 250}
]

st.markdown(f"<h3 style='color:#2E8B57;'>Current Balance: ₹{balance}</h3>", unsafe_allow_html=True)

styled_table = pd.DataFrame(transactions)
st.dataframe(styled_table.style.set_properties(**{'background-color': '#f0f8ff',
                                                   'color': '#000080',
                                                   'border-color': 'white'}))

# ---------------- Stock Market Section ----------------
st.markdown("""
    <h2 style='color: #FF6347;'>📈 Stock Market Info</h2>
""", unsafe_allow_html=True)

# Live indices
nifty = yf.Ticker("^NSEI")
sensex = yf.Ticker("^BSESN")

nifty_price = nifty.history(period="1d").iloc[-1]['Close']
sensex_price = sensex.history(period="1d").iloc[-1]['Close']

st.success(f"Nifty 50: ₹{nifty_price:.2f}")
st.info(f"Sensex: ₹{sensex_price:.2f}")

# ---------------- Stock Search ----------------
st.markdown("""
    <h2 style='color: #4169E1;'>🔍 Search for a Stock</h2>
""", unsafe_allow_html=True)

# Sample stock name-to-symbol dictionary
stock_map = {
    "Reliance": "RELIANCE.NS",
    "Infosys": "INFY.NS",
    "TCS": "TCS.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Wipro": "WIPRO.NS",
    "HCL Technologies": "HCLTECH.NS"
}

query = st.text_input("Enter stock name:", "Infosys")
suggestions = [name for name in stock_map if query.lower() in name.lower()]

if suggestions:
    selected = st.selectbox("Did you mean:", suggestions)
    symbol = stock_map[selected]

    stock = yf.Ticker(symbol)
    data = stock.history(period="5d")
    current_price = data.iloc[-1]['Close']
    previous_close = data.iloc[-2]['Close']
    change = current_price - previous_close
    pct_change = (change / previous_close) * 100

    st.markdown(f"<h4 style='color:#800080;'>{selected} ({symbol})</h4>", unsafe_allow_html=True)
    st.markdown(f"<p style='color:#000080;'>Price: ₹{current_price:.2f} | Change: {change:+.2f} ({pct_change:+.2f}%)</p>", unsafe_allow_html=True)
    st.line_chart(data['Close'])
else:
    st.warning("No stock matched your input.")